name: Publicar Nova Release

# Gatilho: Executa somente quando uma tag no formato v*.*.* é criada e enviada
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publicar-release:
    runs-on: ubuntu-latest
    permissions:
      # Permissão necessária para a action poder criar uma Release no seu repositório
      contents: write

    steps:
      # 1. Baixa o código do repositório para a máquina virtual da Action
      - name: Checkout do Código
        uses: actions/checkout@v4

      # 2. Configura o ambiente Java (JDK 17)
      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Executa os testes e empacota o projeto em um arquivo .jar
      - name: Compilar e Empacotar com Maven
        run: mvn clean package

      # 4. Cria a Release e anexa o(s) arquivo(s) .jar da pasta 'target'
      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          # Esta linha encontra o .jar dentro da pasta 'target' e o anexa
          files: target/*.jar
