name: Publicar Nova Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publicar-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      #
      # PASSO 1: OBRIGATÓRIO - Baixar o código primeiro!
      #
      - name: Checkout do Código
        uses: actions/checkout@v4

      #
      # PASSO 2: Agora sim o setup-java pode encontrar o pom.xml para o cache
      #
      - name: Configurar JDK 17 e Cache do Maven
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # <-- Esta linha precisa que o pom.xml já exista no ambiente

      #
      # PASSO 3: O resto do seu workflow continua normalmente
      #
      - name: Compilar e Empacotar com Maven
        run: mvn clean package

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar
