name: Release Automatizada (Node.js)

# Gatilho: Executa somente quando uma tag no formato v*.*.* é criada e enviada
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  criar-release:
    runs-on: ubuntu-latest
    permissions:
      # Permissão necessária para a action poder criar uma Release
      contents: write

    steps:
      # 1. Baixa o código do repositório para a máquina da Action
      - name: Checkout do Código
        uses: actions/checkout@v4

      # 2. Configura o ambiente Node.js (esta action é muito estável)
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Define a versão do Node.js
          cache: 'npm'       # Habilita o cache das dependências para builds mais rápidos

      # 3. Instala as dependências do projeto definidas no package.json
      - name: Instalar Dependências
        run: npm install

      # 4. Executa o script "test" do package.json para garantir a qualidade
      - name: Rodar Testes
        run: npm test

      # 5. Cria a Release e anexa todo o código-fonte em um arquivo .zip
      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          # A action automaticamente cria um .zip e um .tar.gz com todo o código
          # da tag. Não precisa especificar arquivos, é mais simples e garantido.
          generate_release_notes: true # Opcional: Gera notas da release automaticamente
